<h2> ======================================================</h2>
 <h1>MA477 - Theory and Applications of Data Science</h1> 
  <h1>Lesson 2: Introduction to NumPy</h1> 
 
 <h4>Dr. Valmir Bucaj</h4>
 <br>
 United States Military Academy, West Point, AY20-2
<h2>=======================================================</h2>

In [3]:
import numpy as np

<h2>==================================================</h2>
<br>
<h1>HOMEWORK #1</h1>

<h2>=================================================</h2>

<h3> Complete the following exercises. Document your code as necessary.</h3>
<br>

<ol>
<li><font size=3> Create a 5 by 7 numpy array of random integers with values between 3 and 11 inclusive. Then do the following:
    <ol> <li>Check the data type of the array</li>
        <li>Find the maximum of the entire array</li>
        <li>Find the minimum value of each row</li>
        <li>Find the index where the minimum value of each row occurs</li>
    </ol></font></li>
</ol>

In [13]:
#Your code for part A of Exercise 1 goes here
arr = np.random.randint(3,12, size = (5,7))
arr.dtype

dtype('int32')

In [5]:
#Your code for part B of Exercise 1 goes here
arr.max()

11

In [11]:
#Your code for part C of Exercise 1 goes here
arr.min(axis = 1)

array([3, 3, 4, 5, 4])

In [12]:
#Your code for part D of Exercise 1 goes here
arr.argmin(axis = 1)

array([2, 2, 3, 3, 0], dtype=int64)

<ol start='2'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])
```    
</ol>

In [15]:
#Your code for Exercise 2 goes here
arr2 = np.arange(4,100,5)
arr2

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])

<ol start='3'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [17]:
#Your code for Exercise 3 goes here
arr3 = arr2.reshape(4,5)
arr3

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

<ol start='4'>
   
<li> <font size='3'>Create a 4 by 2 by 3 array of normally distributed values</font></li>
   
</ol>

In [19]:
#Your code for Exercise 4 goes here
np.random.randn(4,2,3)

array([[[ 0.45790846,  1.2512242 ,  0.16029502],
        [-0.11796284, -0.52798859, -0.61451474]],

       [[-1.28470157,  0.12820363,  0.38348055],
        [-0.06427985,  0.23159876, -1.37496694]],

       [[-1.00029822,  0.24396938,  1.37327389],
        [ 1.11362865, -0.25991776, -0.88077345]],

       [[ 0.04339206,  0.21398316, -0.01797904],
        [-0.3964454 , -0.29656388,  1.55222069]]])

<ol start='5'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array(including the correct
    data type): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [23]:
#Your code for Exercise 5 goes here
np.eye(6,k = -2, dtype = int)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

<ol start='6'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Enter the code below that selects only the last four elements:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

In [26]:
#Your code for part A of Exercise 6 goes here
arr6 = np.arange(3,34,2)
arr6[-4:]

array([27, 29, 31, 33])

In [29]:
#Your code for part B of Exercise 6 goes here
arr6[arr6%3==0]

array([ 3,  9, 15, 21, 27, 33])

<ol start='7'>
   
<li> <font size='3'>Given the 2D numpy array below </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Enter the code below that selects the element 72 on the last row</li>
    <br>
   <li>Enter the code below that selects the following subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

In [32]:
#Your code for part A of Exercise 7 goes here
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
arr_2d[4][5]

72

In [34]:
#Your code for part B of Exercise 7 goes here
arr_2d[1:-1,:]

array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])

<ol start='8'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Enter the code that selects all elements larger than 7 and smaller than 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Enter the code below that selects all even integers larger than 11 and smaller than 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

In [36]:
#Your code for part A of Exercise 8 goes here
arr8 = np.arange(1,50,3)
arr8[(arr8 > 7) & (arr8 < 43)]

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [37]:
#Your code for part B of Exercise 8 goes here
arr8[(arr8 > 11) & (arr8 < 45) & (arr8%2==0)]

array([16, 22, 28, 34, 40])

<ol start='9'>
   
<li> <font size='3'>Create a 1D uniformly distributed array with 20 elements and compute: </font></li>


<ol>
    <li> Mean</li>

   <li>Standard Deviation</li>
   
   <li>Median</li>
   
   <li>Mean of its log values</li>
</ol>
</ol>

In [98]:
#Your code for part A of Exercise 9 goes here
arr9 = np.random.rand(20)
arr9.mean()

0.5278077160849707

In [47]:
#Your code for part B of Exercise 9 goes here
arr9.std()

0.22755929500444896

In [99]:
#Your code for part C of Exercise 9 goes here
arr9.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [50]:
#Your code for part D of Exercise 9 goes here
np.log10(arr9).mean()

-0.4530670412299608

<ol start='10'>
   
<li> <font size='3'>Write a function that:</font></li>
    <ol>
    <br>
   <li> takes a 1D Numpy array as input and prints out the <b>reversed</b> array with element type float</li>

For example, if you input the following array into your function
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
your function should print out

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> takes a 2D Numpy array as input and prints out a copy of the input array <b> flattened</b> to one dimension</li>

For example if the input array is:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
the output of your function should be
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

In [71]:
#Your code for part A of Exercise 10 goes here
def reverse(arr):
    new_arr = np.arange(0)
    for n in arr:
        new_arr = np.insert(new_arr, 0, n)
    new_arr = new_arr.astype('float64')
    return(new_arr)

In [95]:
#Your code for part A of Exercise 10 goes here
def flatten(arr):
    x = 0
    y = 0
    for n in arr:
        x += 1
    for n in arr[0]:
        y += 1
    z = x * y
    new_arr = arr.reshape(1,z)
    return(new_arr[0])